### ISSUE TITLE
Search a specific addon by its name.

### ISSUE THREAD

**Issue by waylaa** [AndrewToaster/ForgedCurse#12]
**Is your feature request related to a problem? Please describe.**
I haven't found a way to search an addon only by using its name.

**Describe the solution you'd like**
A nice solution would be to provide a SearchAddonByName(string modName) method inside the 'Addons' property. That way, if i want to get information about a specific mod,  for example, Biomes O' Plenty, i can just call SearchAddonByName("Biomes O' Plenty") which will return an Addon class containg information about the mod itself.

**Additional context**
If there is already a way to do what i am suggesting, it would be great if it could be added to the wiki. I know the wiki has already one example of searching addons but it only works for getting random mods, for example, the top 10 most popular ones.

**Comment by AndrewToaster** [comment]
There is a Name property inside the AddonQueryBuilder, it's just missing the With() method. Afaik that should be it

**Comment by waylaa** [comment]
Found it, thanks for helping.
