### ISSUE TITLE
client.GetMinecraftVersions() couses System.AggregateException.

### ISSUE THREAD

**Issue by OwczarekGit** [AndrewToaster/ForgedCurse#6]
**Describe the bug**
When trying to get minecraft versions using  ForgeClient's GetMinecraftVersions the exception is thrown(see the screenshot below). It cannot deserialize JSON.

**To Reproduce**
1. Create ForgeClient instance.
2. Invoke GetMinecraftVersions on the client instance. 
3. The exception is thrown.

**Expected behavior**
Get the list  of minecraft versions.

**Screenshots**

![image](https://user-images.githubusercontent.com/32412218/118608594-25265000-b7ba-11eb-8026-92137b214e4c.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux

**Additional context**
Invoking GetMinecraftVersion on client works as expected.

**Comment by AndrewToaster** [comment]
The error was the i was parsing an array into an object. Should be fixed now
