### ISSUE TITLE
Addon variable type 

### ISSUE THREAD

**Issue by TechPenguineer** [AndrewToaster/ForgedCurse#8]
Im having trouble using the addon variable type. Im using the example you have in the readme but it gives me this error

```
The type or namespace "Addon" can not be found
```

this is happening on Windows 10.

**Comment by AndrewToaster** [comment]
Hello there, could you please elaborate further (e.g. showing code that throws the errors). From what i can see you may be missing an `using` directive. AFAIK It should be 
```csharp
using ForgedCurse.Json;
```

**Comment by TechPenguineer** [comment]
Hello! Yes sorry. So I'm following the reference your documentation. It's pretty much saying the variable type "Addon" doesn't exist. I tried that import you gave me but it sent back "the namespace Json does not exist"

**Comment by AndrewToaster** [comment]
Are you using ForgedCurse 2.0, because in older versions it's setup differently? I would recommend using NuGet to get ForgedCurse. I will make another release with the ver. 2.0 DLL file. Try using that one or from NuGet

**Comment by TechPenguineer** [comment]
Yes I'm using an older version. I upgraded to the newest and it still happens. Not sure why.

**Comment by AndrewToaster** [comment]
Would you please share the code that causes the issue, it is quite difficult for me figure out what is wrong without seeing it.
